#include <stdio.h>

#include "parser.h"
#include "front.h"

static void error();

/* expr
* <expr> -> <rexp> {(&& | ||) <rexp>)
*/
void expr() {

	printf("Enter <expr>\n");

	rexp();
	while (nextToken == LOGIC_MULT || nextToken == LOGIC_ADD) {
		lex();
		rexp();
	}

	printf("Exit <expr>\n");

}

/* rexp
* <rexp> -> <aexp> {(== | != | < | >) <aexp>)
*/
void rexp() {

	printf("Enter <rexp>\n");

	aexp();
	while (nextToken == COM_SAME || nextToken == COM_DIFF || nextToken == RIGHT_BIG || nextToken == LEFT_BIG) {
		lex();
		aexp();
	}

	printf("Exit <rexp>\n");

}

/* aexp
 * Parses strings in the language generated by the rule:
 * <aexp> -> <term> {(+ | -) <term>}
 */
void aexp() 
{
    printf("Enter <aexp>\n");

    /* Parse the first term */
    term();

    /* As long as the next token is + or -, get
    the next token and parse the next term */
    while (nextToken == ADD_OP || nextToken == SUB_OP) {
        lex();
        term();
    }

    printf("Exit <aexp>\n");
} /* End of function aexp */

/* term
 * Parses strings in the language generated by the rule:
 * <term> -> <factor> {(* | /) <factor>)
 */
void term() 
{
    printf("Enter <term>\n");
    /* Parse the first factor */
    factor();
    /* As long as the next token is * or /, get the
    next token and parse the next factor */
    while (nextToken == MULT_OP || nextToken == DIV_OP) {
            lex();
            factor();
    }
    printf("Exit <term>\n");
} /* End of function term */

/* factor
 * Parses strings in the language generated by the rule:
 * <factor> -> id | int_constant | ( <expr> ) | !<factor>
 * */
void factor() 
{
    printf("Enter <factor>\n");
    /* Determine which RHS */
    if (nextToken == IDENT || nextToken == INT_LIT) {
        lex(); /* Get the next token */
    }
	else if (nextToken == NOT) { // !<factor>
		lex();
		factor();
	}
	else {
        /* If the RHS is (<expr>), call lex to pass over the 
        left parenthesis, call expr, and check for the right 
        parenthesis */
        if (nextToken == LEFT_PAREN) {
            lex(); 
            expr();

            if (nextToken == RIGHT_PAREN) {
                lex(); 
            } else { 
                error();
            }
        } /* End of if (nextToken == ... */
        /* It was not an id, an integer literal, or a left parenthesis */
        else 
        { 
            error(); 
        }
    } /* End of else */
    printf("Exit <factor>\n");;
} /* End of function factor */

static void error() 
{
    printf("Error (more is desired, but not implemented).\n");
}

